# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f0c4550ad5d7ccc3510a9a0bc148cb9"
name = "weee-calculator-app"
handle = "weee-calculator-app-1"
application_url = "https://paraguay-cleared-meant-womens.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingforstoreistest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://paraguay-cleared-meant-womens.trycloudflare.com/auth/callback",
  "https://paraguay-cleared-meant-womens.trycloudflare.com/auth/shopify/callback",
  "https://paraguay-cleared-meant-womens.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
